import type { Database as GeneratedDatabase } from "./database.types";

/**
 * The generated types plus corrections the generator can't infer.
 * Import `Database` from here, never from `database.types.ts` (regenerated by `pnpm db:types`).
 */

/** Columns set by the `activities_derive_fields` trigger; clients never write them. */
type ActivityDerivedColumn = "local_date" | "local_hour" | "life_area_id";

type GeneratedPublic = GeneratedDatabase["public"];
type GeneratedTables = GeneratedPublic["Tables"];
type ActivitiesTable = GeneratedTables["activities"];

export type Database = Omit<GeneratedDatabase, "public"> & {
  public: Omit<GeneratedPublic, "Tables"> & {
    Tables: Omit<GeneratedTables, "activities"> & {
      activities: Omit<ActivitiesTable, "Insert" | "Update"> & {
        Insert: Omit<ActivitiesTable["Insert"], ActivityDerivedColumn>;
        Update: Omit<ActivitiesTable["Update"], ActivityDerivedColumn>;
      };
    };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];
export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T];
