import type { Database as GeneratedDatabase } from "./database.types";

/**
 * The generated types plus corrections the generator can't infer.
 * Import `Database` from here, never from `database.types.ts` (regenerated by `pnpm db:types`).
 */

type GeneratedPublic = GeneratedDatabase["public"];
type GeneratedTables = GeneratedPublic["Tables"];

/** A table whose trigger-derived columns can't be written by clients. */
type WithDerived<T extends { Insert: object; Update: object }, Derived extends PropertyKey> = Omit<
  T,
  "Insert" | "Update"
> & {
  Insert: Omit<T["Insert"], Derived>;
  Update: Omit<T["Update"], Derived>;
};

export type Database = Omit<GeneratedDatabase, "public"> & {
  public: Omit<GeneratedPublic, "Tables"> & {
    Tables: Omit<GeneratedTables, "activities" | "outcomes"> & {
      // activities_derive_fields
      activities: WithDerived<GeneratedTables["activities"], "local_date" | "local_hour" | "life_area_id">;
      // outcomes_derive_local_date
      outcomes: WithDerived<GeneratedTables["outcomes"], "local_date">;
    };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];
export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T];
